### ISSUE TITLE
No config method exposed

### ISSUE THREAD

**Issue by cefn** [zekizeki/nodeDockerMachine#9]
On the npmjs site at https://www.npmjs.com/package/dockermachine#the-following-docker-machine-methods-are-implemented it indicates that 

> The following docker-machine methods are implemented
> active    Get the active machine name
> create    Create a machine
> config    Print the connection config for machine
> inspect   Inspect information about a machine
> ip    Get the IP address of a machine
> kill  Kill a machine
> ls    List machines
> regenerate-certs  Regenerate TLS Certificates for a machine
> restart   Restart a machine
> rm    Remove a machine
> ssh   Log into or run a command on a machine with SSH
> start Start a machine
> stop  Stop a machine
> upgrade   Upgrade a machine to the latest version of Docker

However, from the latest NPM this is what I see, and 'config' at least is absent...

```
Object.keys(dockermachine)
[ 'ls',
  'create',
  'rm',
  'active',
  'inspect',
  'regenerateCerts',
  'kill',
  'start',
  'stop',
  'restart',
  'upgrade',
  'ssh',
  'url',
  'ip' ]
> "config" in dockermachine
false
```

I guess config was replaced with 'url' ?

**Comment by zekizeki** [comment]
Thanks for pointing that out, I've removed config from the list of supported methods.
